export const defaultFunds = [
  // Demo incomes

  {
    key: Math.random().toString(),
    content: "full time job payment",
    date: new Date(2022, 11, 10),
    amount: 4000,
    option: "salary",
    type: "income",
  },
  {
    key: Math.random().toString(),
    content: "full time job payment",
    date: new Date(2022, 10, 10),
    amount: 4000,
    option: "salary",
    type: "income",
  },
  {
    key: Math.random().toString(),
    content: "full time job payment",
    date: new Date(2022, 9, 10),
    amount: 4000,
    option: "salary",
    type: "income",
  },
  {
    key: Math.random().toString(),
    content: "full time job payment",
    date: new Date(2022, 8, 10),
    amount: 4000,
    option: "salary",
    type: "income",
  },
  {
    key: Math.random().toString(),
    content: "full time job payment",
    date: new Date(2022, 7, 10),
    amount: 4000,
    option: "salary",
    type: "income",
  },
  {
    key: Math.random().toString(),
    content: "full time job payment",
    date: new Date(2022, 6, 10),
    amount: 4000,
    option: "salary",
    type: "income",
  },
  {
    key: Math.random().toString(),
    content: "full time job payment",
    date: new Date(2022, 5, 10),
    amount: 4000,
    option: "salary",
    type: "income",
  },
  {
    key: Math.random().toString(),
    content: "full time job payment",
    date: new Date(2022, 4, 10),
    amount: 4000,
    option: "salary",
    type: "income",
  },
  {
    key: Math.random().toString(),
    content: "full time job payment",
    date: new Date(2022, 3, 10),
    amount: 4000,
    option: "salary",
    type: "income",
  },
  {
    key: Math.random().toString(),
    content: "full time job payment",
    date: new Date(2022, 2, 10),
    amount: 4000,
    option: "salary",
    type: "income",
  },
  {
    key: Math.random().toString(),
    content: "full time job payment",
    date: new Date(2022, 1, 10),
    amount: 4000,
    option: "salary",
    type: "income",
  },
  {
    key: Math.random().toString(),
    content: "full time job payment",
    date: new Date(2022, 0, 10),
    amount: 4000,
    option: "salary",
    type: "income",
  },
  {
    key: Math.random().toString(),
    content: "bank deposit revenue",
    date: new Date(2022, 11, 16),
    amount: 48.96,
    option: "interest",
    type: "income",
  },
  {
    key: Math.random().toString(),
    content: "bank deposit revenue",
    date: new Date(2022, 5, 16),
    amount: 43.96,
    option: "interest",
    type: "income",
  },
  {
    key: Math.random().toString(),
    content: "old TV sale",
    date: new Date(2022, 8, 4),
    amount: 550,
    option: "resale",
    type: "income",
  },
  {
    key: Math.random().toString(),
    content: "old jacket sale",
    date: new Date(2022, 3, 22),
    amount: 80,
    option: "resale",
    type: "income",
  },
  {
    key: Math.random().toString(),
    content: "stocks dividend",
    date: new Date(2022, 4, 11),
    amount: 119.23,
    option: "capital",
    type: "income",
  },
  {
    key: Math.random().toString(),
    content: "christmas bonus",
    date: new Date(2022, 11, 16),
    amount: 750,
    option: "salary",
    type: "income",
  },

  // Demo expenses

  {
    key: Math.random().toString(),
    content: "flat rent",
    date: new Date(2022, 11, 10),
    amount: 1800,
    option: "fixed",
    type: "expense",
  },
  {
    key: Math.random().toString(),
    content: "flat rent",
    date: new Date(2022, 10, 10),
    amount: 1800,
    option: "fixed",
    type: "expense",
  },
  {
    key: Math.random().toString(),
    content: "flat rent",
    date: new Date(2022, 9, 10),
    amount: 1800,
    option: "fixed",
    type: "expense",
  },
  {
    key: Math.random().toString(),
    content: "flat rent",
    date: new Date(2022, 8, 10),
    amount: 1800,
    option: "fixed",
    type: "expense",
  },
  {
    key: Math.random().toString(),
    content: "flat rent",
    date: new Date(2022, 7, 10),
    amount: 1800,
    option: "fixed",
    type: "expense",
  },
  {
    key: Math.random().toString(),
    content: "flat rent",
    date: new Date(2022, 6, 10),
    amount: 1800,
    option: "fixed",
    type: "expense",
  },
  {
    key: Math.random().toString(),
    content: "flat rent",
    date: new Date(2022, 5, 10),
    amount: 1800,
    option: "fixed",
    type: "expense",
  },
  {
    key: Math.random().toString(),
    content: "flat rent",
    date: new Date(2022, 4, 10),
    amount: 1800,
    option: "fixed",
    type: "expense",
  },
  {
    key: Math.random().toString(),
    content: "flat rent",
    date: new Date(2022, 3, 10),
    amount: 1800,
    option: "fixed",
    type: "expense",
  },
  {
    key: Math.random().toString(),
    content: "flat rent",
    date: new Date(2022, 2, 10),
    amount: 1800,
    option: "fixed",
    type: "expense",
  },
  {
    key: Math.random().toString(),
    content: "flat rent",
    date: new Date(2022, 1, 10),
    amount: 1800,
    option: "fixed",
    type: "expense",
  },
  {
    key: Math.random().toString(),
    content: "flat rent",
    date: new Date(2022, 0, 10),
    amount: 1800,
    option: "fixed",
    type: "expense",
  },
  {
    key: Math.random().toString(),
    content: "regular grocery",
    date: new Date(2022, 11, 3),
    amount: 176.43,
    option: "grocery",
    type: "expense",
  },
  {
    key: Math.random().toString(),
    content: "regular grocery",
    date: new Date(2022, 10, 5),
    amount: 276.12,
    option: "grocery",
    type: "expense",
  },
  {
    key: Math.random().toString(),
    content: "regular grocery",
    date: new Date(2022, 9, 4),
    amount: 306.01,
    option: "grocery",
    type: "expense",
  },
  {
    key: Math.random().toString(),
    content: "regular grocery",
    date: new Date(2022, 8, 2),
    amount: 218.12,
    option: "grocery",
    type: "expense",
  },
  {
    key: Math.random().toString(),
    content: "regular grocery",
    date: new Date(2022, 7, 4),
    amount: 115.73,
    option: "grocery",
    type: "expense",
  },
  {
    key: Math.random().toString(),
    content: "regular grocery",
    date: new Date(2022, 6, 6),
    amount: 143.83,
    option: "grocery",
    type: "expense",
  },
  {
    key: Math.random().toString(),
    content: "regular grocery",
    date: new Date(2022, 5, 5),
    amount: 101.15,
    option: "grocery",
    type: "expense",
  },
  {
    key: Math.random().toString(),
    content: "regular grocery",
    date: new Date(2022, 4, 3),
    amount: 89.78,
    option: "grocery",
    type: "expense",
  },
  {
    key: Math.random().toString(),
    content: "regular grocery",
    date: new Date(2022, 3, 4),
    amount: 305.85,
    option: "grocery",
    type: "expense",
  },
  {
    key: Math.random().toString(),
    content: "regular grocery",
    date: new Date(2022, 2, 5),
    amount: 212.84,
    option: "grocery",
    type: "expense",
  },
  {
    key: Math.random().toString(),
    content: "regular grocery",
    date: new Date(2022, 1, 2),
    amount: 246.29,
    option: "grocery",
    type: "expense",
  },
  {
    key: Math.random().toString(),
    content: "regular grocery",
    date: new Date(2022, 0, 4),
    amount: 129.23,
    option: "grocery",
    type: "expense",
  },
  {
    key: Math.random().toString(),
    content: "regular grocery",
    date: new Date(2022, 11, 23),
    amount: 152.98,
    option: "grocery",
    type: "expense",
  },
  {
    key: Math.random().toString(),
    content: "regular grocery",
    date: new Date(2022, 10, 25),
    amount: 202.14,
    option: "grocery",
    type: "expense",
  },
  {
    key: Math.random().toString(),
    content: "regular grocery",
    date: new Date(2022, 9, 24),
    amount: 256.92,
    option: "grocery",
    type: "expense",
  },
  {
    key: Math.random().toString(),
    content: "regular grocery",
    date: new Date(2022, 8, 22),
    amount: 175.43,
    option: "grocery",
    type: "expense",
  },
  {
    key: Math.random().toString(),
    content: "regular grocery",
    date: new Date(2022, 7, 24),
    amount: 139.84,
    option: "grocery",
    type: "expense",
  },
  {
    key: Math.random().toString(),
    content: "regular grocery",
    date: new Date(2022, 6, 26),
    amount: 212.09,
    option: "grocery",
    type: "expense",
  },
  {
    key: Math.random().toString(),
    content: "regular grocery",
    date: new Date(2022, 5, 25),
    amount: 201.43,
    option: "grocery",
    type: "expense",
  },
  {
    key: Math.random().toString(),
    content: "regular grocery",
    date: new Date(2022, 4, 23),
    amount: 305.98,
    option: "grocery",
    type: "expense",
  },
  {
    key: Math.random().toString(),
    content: "regular grocery",
    date: new Date(2022, 3, 24),
    amount: 402.12,
    option: "grocery",
    type: "expense",
  },
  {
    key: Math.random().toString(),
    content: "regular grocery",
    date: new Date(2022, 2, 25),
    amount: 187.65,
    option: "grocery",
    type: "expense",
  },
  {
    key: Math.random().toString(),
    content: "regular grocery",
    date: new Date(2022, 1, 22),
    amount: 143.24,
    option: "grocery",
    type: "expense",
  },
  {
    key: Math.random().toString(),
    content: "regular grocery",
    date: new Date(2022, 0, 24),
    amount: 187.54,
    option: "grocery",
    type: "expense",
  },
  {
    key: Math.random().toString(),
    content: "regular grocery",
    date: new Date(2022, 11, 13),
    amount: 225.43,
    option: "grocery",
    type: "expense",
  },
  {
    key: Math.random().toString(),
    content: "regular grocery",
    date: new Date(2022, 10, 15),
    amount: 126.42,
    option: "grocery",
    type: "expense",
  },
  {
    key: Math.random().toString(),
    content: "regular grocery",
    date: new Date(2022, 9, 14),
    amount: 186.13,
    option: "grocery",
    type: "expense",
  },
  {
    key: Math.random().toString(),
    content: "regular grocery",
    date: new Date(2022, 8, 12),
    amount: 79.23,
    option: "grocery",
    type: "expense",
  },
  {
    key: Math.random().toString(),
    content: "regular grocery",
    date: new Date(2022, 7, 14),
    amount: 149.23,
    option: "grocery",
    type: "expense",
  },
  {
    key: Math.random().toString(),
    content: "regular grocery",
    date: new Date(2022, 6, 16),
    amount: 187.54,
    option: "grocery",
    type: "expense",
  },
  {
    key: Math.random().toString(),
    content: "regular grocery",
    date: new Date(2022, 5, 15),
    amount: 164.33,
    option: "grocery",
    type: "expense",
  },
  {
    key: Math.random().toString(),
    content: "regular grocery",
    date: new Date(2022, 4, 13),
    amount: 152.92,
    option: "grocery",
    type: "expense",
  },
  {
    key: Math.random().toString(),
    content: "regular grocery",
    date: new Date(2022, 3, 14),
    amount: 204.12,
    option: "grocery",
    type: "expense",
  },
  {
    key: Math.random().toString(),
    content: "regular grocery",
    date: new Date(2022, 2, 15),
    amount: 143.8,
    option: "grocery",
    type: "expense",
  },
  {
    key: Math.random().toString(),
    content: "regular grocery",
    date: new Date(2022, 1, 12),
    amount: 129.23,
    option: "grocery",
    type: "expense",
  },
  {
    key: Math.random().toString(),
    content: "regular grocery",
    date: new Date(2022, 0, 14),
    amount: 145.62,
    option: "grocery",
    type: "expense",
  },

  {
    key: Math.random().toString(),
    content: "car fuel",
    date: new Date(2022, 11, 3),
    amount: 256.88,
    option: "transport",
    type: "expense",
  },
  {
    key: Math.random().toString(),
    content: "car fuel",
    date: new Date(2022, 10, 8),
    amount: 276.45,
    option: "transport",
    type: "expense",
  },
  {
    key: Math.random().toString(),
    content: "car fuel",
    date: new Date(2022, 9, 9),
    amount: 225.48,
    option: "transport",
    type: "expense",
  },
  {
    key: Math.random().toString(),
    content: "car fuel",
    date: new Date(2022, 8, 23),
    amount: 294.78,
    option: "transport",
    type: "expense",
  },
  {
    key: Math.random().toString(),
    content: "car fuel",
    date: new Date(2022, 7, 3),
    amount: 300.18,
    option: "transport",
    type: "expense",
  },
  {
    key: Math.random().toString(),
    content: "car fuel",
    date: new Date(2022, 6, 3),
    amount: 315.72,
    option: "transport",
    type: "expense",
  },
  {
    key: Math.random().toString(),
    content: "car fuel",
    date: new Date(2022, 6, 27),
    amount: 187.23,
    option: "transport",
    type: "expense",
  },
  {
    key: Math.random().toString(),
    content: "car fuel",
    date: new Date(2022, 5, 12),
    amount: 281.15,
    option: "transport",
    type: "expense",
  },
  {
    key: Math.random().toString(),
    content: "car fuel",
    date: new Date(2022, 4, 11),
    amount: 289.78,
    option: "transport",
    type: "expense",
  },
  {
    key: Math.random().toString(),
    content: "car fuel",
    date: new Date(2022, 3, 4),
    amount: 245.85,
    option: "transport",
    type: "expense",
  },
  {
    key: Math.random().toString(),
    content: "car fuel",
    date: new Date(2022, 2, 22),
    amount: 312.84,
    option: "transport",
    type: "expense",
  },
  {
    key: Math.random().toString(),
    content: "car fuel",
    date: new Date(2022, 1, 17),
    amount: 216.22,
    option: "transport",
    type: "expense",
  },
  {
    key: Math.random().toString(),
    content: "car fuel",
    date: new Date(2022, 0, 6),
    amount: 269.23,
    option: "transport",
    type: "expense",
  },
  {
    key: Math.random().toString(),
    content: "new trausers",
    date: new Date(2022, 11, 15),
    amount: 149.99,
    option: "clothes",
    type: "expense",
  },
  {
    key: Math.random().toString(),
    content: "new jacket",
    date: new Date(2022, 10, 5),
    amount: 199.99,
    option: "clothes",
    type: "expense",
  },
  {
    key: Math.random().toString(),
    content: "new shoes",
    date: new Date(2022, 9, 14),
    amount: 349.99,
    option: "clothes",
    type: "expense",
  },
  {
    key: Math.random().toString(),
    content: "new belt",
    date: new Date(2022, 8, 2),
    amount: 89.99,
    option: "clothes",
    type: "expense",
  },
  {
    key: Math.random().toString(),
    content: "new shirt",
    date: new Date(2022, 7, 7),
    amount: 69.99,
    option: "clothes",
    type: "expense",
  },
  {
    key: Math.random().toString(),
    content: "new sunglasses",
    date: new Date(2022, 6, 28),
    amount: 129.99,
    option: "clothes",
    type: "expense",
  },
  {
    key: Math.random().toString(),
    content: "new shoes",
    date: new Date(2022, 5, 11),
    amount: 199.99,
    option: "clothes",
    type: "expense",
  },
  {
    key: Math.random().toString(),
    content: "new jeans",
    date: new Date(2022, 4, 25),
    amount: 149.99,
    option: "clothes",
    type: "expense",
  },
  {
    key: Math.random().toString(),
    content: "new original hoodie",
    date: new Date(2022, 3, 7),
    amount: 499.9,
    option: "clothes",
    type: "expense",
  },
  {
    key: Math.random().toString(),
    content: "new winter gloves",
    date: new Date(2022, 2, 5),
    amount: 59.99,
    option: "clothes",
    type: "expense",
  },
  {
    key: Math.random().toString(),
    content: "winter socks & underwear",
    date: new Date(2022, 1, 15),
    amount: 79.99,
    option: "clothes",
    type: "expense",
  },
  {
    key: Math.random().toString(),
    content: "new trausers",
    date: new Date(2022, 0, 18),
    amount: 229.99,
    option: "clothes",
    type: "expense",
  },
  {
    key: Math.random().toString(),
    content: "energy & water payment",
    date: new Date(2022, 11, 8),
    amount: 187.24,
    option: "bills",
    type: "expense",
  },
  {
    key: Math.random().toString(),
    content: "energy & water payment",
    date: new Date(2022, 10, 8),
    amount: 176.22,
    option: "bills",
    type: "expense",
  },
  {
    key: Math.random().toString(),
    content: "energy & water payment",
    date: new Date(2022, 9, 8),
    amount: 208.13,
    option: "bills",
    type: "expense",
  },
  {
    key: Math.random().toString(),
    content: "energy & water payment",
    date: new Date(2022, 8, 8),
    amount: 198.23,
    option: "bills",
    type: "expense",
  },
  {
    key: Math.random().toString(),
    content: "energy & water payment",
    date: new Date(2022, 7, 8),
    amount: 168.23,
    option: "bills",
    type: "expense",
  },
  {
    key: Math.random().toString(),
    content: "energy & water payment",
    date: new Date(2022, 6, 8),
    amount: 190.89,
    option: "bills",
    type: "expense",
  },
  {
    key: Math.random().toString(),
    content: "energy & water payment",
    date: new Date(2022, 5, 8),
    amount: 199.13,
    option: "bills",
    type: "expense",
  },
  {
    key: Math.random().toString(),
    content: "energy & water payment",
    date: new Date(2022, 4, 8),
    amount: 179.53,
    option: "bills",
    type: "expense",
  },
  {
    key: Math.random().toString(),
    content: "energy & water payment",
    date: new Date(2022, 3, 8),
    amount: 204.32,
    option: "bills",
    type: "expense",
  },
  {
    key: Math.random().toString(),
    content: "energy & water payment",
    date: new Date(2022, 2, 8),
    amount: 189.34,
    option: "bills",
    type: "expense",
  },
  {
    key: Math.random().toString(),
    content: "energy & water payment",
    date: new Date(2022, 1, 8),
    amount: 202.98,
    option: "bills",
    type: "expense",
  },
  {
    key: Math.random().toString(),
    content: "energy & water payment",
    date: new Date(2022, 0, 8),
    amount: 179.24,
    option: "bills",
    type: "expense",
  },
  {
    key: Math.random().toString(),
    content: "going out with friends",
    date: new Date(2022, 11, 15),
    amount: 115.43,
    option: "meetings",
    type: "expense",
  },
  {
    key: Math.random().toString(),
    content: "restaurant with parents",
    date: new Date(2022, 10, 22),
    amount: 256.12,
    option: "meetings",
    type: "expense",
  },
  {
    key: Math.random().toString(),
    content: "company paintball event",
    date: new Date(2022, 9, 13),
    amount: 80,
    option: "meetings",
    type: "expense",
  },
  {
    key: Math.random().toString(),
    content: "pub with Tom",
    date: new Date(2022, 8, 17),
    amount: 74.29,
    option: "meetings",
    type: "expense",
  },
  {
    key: Math.random().toString(),
    content: "going out with friends",
    date: new Date(2022, 7, 26),
    amount: 128.59,
    option: "meetings",
    type: "expense",
  },
  {
    key: Math.random().toString(),
    content: "mom's birthday restaurant",
    date: new Date(2022, 6, 6),
    amount: 199.2,
    option: "meetings",
    type: "expense",
  },
  {
    key: Math.random().toString(),
    content: "club with friends",
    date: new Date(2022, 5, 12),
    amount: 164.28,
    option: "meetings",
    type: "expense",
  },
  {
    key: Math.random().toString(),
    content: "hiking with John",
    date: new Date(2022, 4, 29),
    amount: 54.12,
    option: "meetings",
    type: "expense",
  },
  {
    key: Math.random().toString(),
    content: "father's birthday restaurant",
    date: new Date(2022, 3, 16),
    amount: 219.89,
    option: "meetings",
    type: "expense",
  },
  {
    key: Math.random().toString(),
    content: "paul's birthday beer & pizza",
    date: new Date(2022, 2, 2),
    amount: 64.12,
    option: "meetings",
    type: "expense",
  },
  {
    key: Math.random().toString(),
    content: "going out with friends",
    date: new Date(2022, 1, 5),
    amount: 59.87,
    option: "meetings",
    type: "expense",
  },
  {
    key: Math.random().toString(),
    content: "beer with Mike",
    date: new Date(2022, 0, 15),
    amount: 49.9,
    option: "meetings",
    type: "expense",
  },
  {
    key: Math.random().toString(),
    content: "painkillers",
    date: new Date(2022, 11, 2),
    amount: 29.99,
    option: "medicines",
    type: "expense",
  },
  {
    key: Math.random().toString(),
    content: "cough syrup",
    date: new Date(2022, 10, 22),
    amount: 24.99,
    option: "medicines",
    type: "expense",
  },
  {
    key: Math.random().toString(),
    content: "painkillers",
    date: new Date(2022, 9, 28),
    amount: 29.99,
    option: "medicines",
    type: "expense",
  },
  {
    key: Math.random().toString(),
    content: "cough syrup",
    date: new Date(2022, 8, 14),
    amount: 44.99,
    option: "medicines",
    type: "expense",
  },
  {
    key: Math.random().toString(),
    content: "warming ointment",
    date: new Date(2022, 7, 13),
    amount: 49.99,
    option: "medicines",
    type: "expense",
  },
  {
    key: Math.random().toString(),
    content: "painkillers",
    date: new Date(2022, 6, 7),
    amount: 24.99,
    option: "medicines",
    type: "expense",
  },
  {
    key: Math.random().toString(),
    content: "cough syrup",
    date: new Date(2022, 5, 14),
    amount: 44.99,
    option: "medicines",
    type: "expense",
  },
  {
    key: Math.random().toString(),
    content: "fingerprint patches",
    date: new Date(2022, 4, 19),
    amount: 19.99,
    option: "medicines",
    type: "expense",
  },
  {
    key: Math.random().toString(),
    content: "painkillers",
    date: new Date(2022, 3, 12),
    amount: 29.99,
    option: "medicines",
    type: "expense",
  },
  {
    key: Math.random().toString(),
    content: "relief pills",
    date: new Date(2022, 2, 2),
    amount: 36.99,
    option: "medicines",
    type: "expense",
  },
  {
    key: Math.random().toString(),
    content: "cough syrup",
    date: new Date(2022, 1, 15),
    amount: 42.99,
    option: "medicines",
    type: "expense",
  },
  {
    key: Math.random().toString(),
    content: "painkillers",
    date: new Date(2022, 0, 4),
    amount: 24.99,
    option: "medicines",
    type: "expense",
  },
  {
    key: Math.random().toString(),
    content: "cinema tickets & popcorn",
    date: new Date(2022, 11, 22),
    amount: 78.23,
    option: "events",
    type: "expense",
  },
  {
    key: Math.random().toString(),
    content: "rock concert",
    date: new Date(2022, 10, 17),
    amount: 116.22,
    option: "events",
    type: "expense",
  },
  {
    key: Math.random().toString(),
    content: "car trip",
    date: new Date(2022, 9, 16),
    amount: 78.92,
    option: "events",
    type: "expense",
  },
  {
    key: Math.random().toString(),
    content: "cinema tickets & popcorn",
    date: new Date(2022, 8, 17),
    amount: 85.21,
    option: "events",
    type: "expense",
  },
  {
    key: Math.random().toString(),
    content: "music festival",
    date: new Date(2022, 7, 23),
    amount: 287.19,
    option: "events",
    type: "expense",
  },
  {
    key: Math.random().toString(),
    content: "holidays",
    date: new Date(2022, 6, 18),
    amount: 1248.1,
    option: "events",
    type: "expense",
  },
  {
    key: Math.random().toString(),
    content: "football match",
    date: new Date(2022, 6, 12),
    amount: 65.28,
    option: "events",
    type: "expense",
  },
  {
    key: Math.random().toString(),
    content: "cinema tickets & popcorn",
    date: new Date(2022, 5, 29),
    amount: 79.15,
    option: "events",
    type: "expense",
  },
  {
    key: Math.random().toString(),
    content: "stand-up",
    date: new Date(2022, 4, 22),
    amount: 39.99,
    option: "events",
    type: "expense",
  },
  {
    key: Math.random().toString(),
    content: "football match",
    date: new Date(2022, 3, 1),
    amount: 68.12,
    option: "events",
    type: "expense",
  },
  {
    key: Math.random().toString(),
    content: "cinema tickets & popcorn",
    date: new Date(2022, 2, 18),
    amount: 85.12,
    option: "events",
    type: "expense",
  },
  {
    key: Math.random().toString(),
    content: "cinema tickets & popcorn",
    date: new Date(2022, 1, 7),
    amount: 87.23,
    option: "events",
    type: "expense",
  },
  {
    key: Math.random().toString(),
    content: "skiing trip",
    date: new Date(2022, 0, 6),
    amount: 615.29,
    option: "events",
    type: "expense",
  },
  {
    key: Math.random().toString(),
    content: "car engine repair",
    date: new Date(2022, 11, 28),
    amount: 519.9,
    option: "others",
    type: "expense",
  },
  {
    key: Math.random().toString(),
    content: "new car tires",
    date: new Date(2022, 10, 1),
    amount: 269.99,
    option: "others",
    type: "expense",
  },
  {
    key: Math.random().toString(),
    content: "bedroom walls painting",
    date: new Date(2022, 9, 27),
    amount: 138.99,
    option: "others",
    type: "expense",
  },
  {
    key: Math.random().toString(),
    content: "phone screen repair",
    date: new Date(2022, 8, 16),
    amount: 89.99,
    option: "others",
    type: "expense",
  },
  {
    key: Math.random().toString(),
    content: "visit the doctor",
    date: new Date(2022, 7, 30),
    amount: 150,
    option: "others",
    type: "expense",
  },
  {
    key: Math.random().toString(),
    content: "new car batery",
    date: new Date(2022, 6, 12),
    amount: 179.99,
    option: "others",
    type: "expense",
  },
  {
    key: Math.random().toString(),
    content: "visit the doctor",
    date: new Date(2022, 5, 23),
    amount: 200,
    option: "others",
    type: "expense",
  },
  {
    key: Math.random().toString(),
    content: "washing machine repair",
    date: new Date(2022, 4, 3),
    amount: 200,
    option: "others",
    type: "expense",
  },
  {
    key: Math.random().toString(),
    content: "living room wall painting",
    date: new Date(2022, 3, 12),
    amount: 156.99,
    option: "others",
    type: "expense",
  },
  {
    key: Math.random().toString(),
    content: "car tire repair",
    date: new Date(2022, 2, 25),
    amount: 100,
    option: "others",
    type: "expense",
  },
  {
    key: Math.random().toString(),
    content: "volunteer payment",
    date: new Date(2022, 1, 17),
    amount: 40,
    option: "others",
    type: "expense",
  },
  {
    key: Math.random().toString(),
    content: "visit the docotr",
    date: new Date(2022, 0, 26),
    amount: 150,
    option: "others",
    type: "expense",
  },
];
