export const defaultTasks = [
  // Demo tasks December 2022

  {
    key: Math.random().toString(),
    content: "Pay for flat rent",
    date: new Date(2022, 11, 15, 1, 0, 0, 0),
    option: "payments",
    priority: true,
    done: false,
  },
  {
    key: Math.random().toString(),
    content: "Go for christmas shopping",
    date: new Date(2022, 11, 18, 1, 0, 0, 0),
    option: "others",
    priority: false,
    done: false,
  },
  {
    key: Math.random().toString(),
    content: "Gym training",
    date: new Date(2022, 11, 11, 1, 0, 0, 0),
    option: "self-care",
    priority: false,
    done: false,
  },
  {
    key: Math.random().toString(),
    content: "Meeting with a client",
    date: new Date(2022, 11, 20, 1, 0, 0, 0),
    option: "work",
    priority: true,
    done: false,
  },
  {
    key: Math.random().toString(),
    content: "Medical visit",
    date: new Date(2022, 11, 12, 1, 0, 0, 0),
    option: "self-care",
    priority: true,
    done: false,
  },
  {
    key: Math.random().toString(),
    content: "programming project deadline",
    date: new Date(2022, 11, 7, 1, 0, 0, 0),
    option: "learning",
    priority: true,
    done: false,
  },
  {
    key: Math.random().toString(),
    content: "John's birthday",
    date: new Date(2022, 11, 6, 1, 0, 0, 0),
    option: "events",
    priority: false,
    done: false,
  },
];
